[build]
command = "npm run build"
publish = ".next"
base = "."

[build.environment]
NODE_VERSION = "18"
NEXT_TELEMETRY_DISABLED = "1"
NPM_FLAGS = "--shamefully-hoist"

[[plugins]]
package = "@netlify/plugin-nextjs"

# Headers básicos para seguridad
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para assets estáticos
[[headers]]
for = "/_next/static/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/favicon.ico"
[headers.values]
Cache-Control = "public, max-age=86400"
Content-Type = "image/x-icon"
